apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
  namespace: audit-zone
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: host-vol
          mountPath: /host
  volumes:
    - name: host-vol
      hostPath:
        path: /var/log
